ShoeStore.Presentation/Controllers/AdminController.cs
using ShoeShop.Presentation.Interfaces;
using ShoeStore.Models;
using ShoeStore.Presentation.Mappers;
using ShoeStore.Presentation.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoeStore.Presentation.Controllers
{
    public class AdminController : Controller
    {
        private IItemService _itemService;
        private IStoreService _storeService;
        private IStoreItemService _siService;
        private IAvailableSizeService _asService;
        private IPictureService _pictureService;

        private Configuration.Configurations _itemConfig;
        private ItemMapper _itemMapper;
        private StoreMapper _storeMapper;

        public AdminController()
        {
            _itemConfig = new Configuration.Configurations();
            _itemService = _itemConfig.GetItemService();
            _itemMapper = new ItemMapper(_itemConfig);
            _storeService = _itemConfig.GetStoreService();
            _storeMapper = new StoreMapper(_itemConfig);
            _siService = _itemConfig.GetStoreItemService();
            _asService = _itemConfig.GetAvailableSizeService();
            _pictureService = _itemConfig.GetPictureService();
        }
        private bool IsAdmin()
        {
            if(Session["admin"]!=null && (bool)Session["admin"] == true)
            {
                return true;
            }
            return false;
        }
        public ActionResult Index()
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            NewItemVM ni = new NewItemVM();
            ni.AllItems = _itemService.GetAll();
            return View(ni);
        }

        public ActionResult Stores()
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            NewStoreVM ns = new NewStoreVM();
            ns.AllStores = _storeService.GetAll();
            return View(ns);
        }

        public ActionResult Store(Guid id)
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            Store s = _storeService.FindById(id);
            NewStoreVM ns = new NewStoreVM();
            ns.ItemToAdd = new ItemVM();
            ns.Store = _storeMapper.FindItemsForStore(s);
            return View(ns);
        }

        [HttpPost]
        public ActionResult Store(NewStoreVM ns)
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            if (Request.Form["add"] != null)
            {
                //Add form
                if (Validate(ns))
                {
                    StoreItem si = new StoreItem();
                    si.ItemId = ns.ItemToAdd.Id;
                    si.StoreId = ns.Store.Id;
                    si.Price = ns.ItemToAdd.Price;
                    si = _siService.Add(si);
                    AvailableSize ass = new AvailableSize();
                    ass.SIId = si.Id;
                    ass.Size = ns.ItemToAdd.SelectedAverableSize.Size;
                    _asService.Add(ass);
                    return Redirect("/Admin/Store/" + ns.Store.Id.ToString());
                }
            }
            else if (Request.Form["remove"] != null)
            {
                if (Validate(ns))
                {
                    //remove size from item
                    StoreItem si = _siService.FindByStoreIdAndItemId(ns.Store.Id, ns.ItemToAdd.Id);
                    if (si != null)
                    {
                        _asService.RemoveBySIIdAndSize(si.Id, ns.ItemToAdd.SelectedAverableSize.Size);
                        return Redirect("/Admin/Store/" + ns.Store.Id.ToString());
                    }
                }
            }
            return Redirect("/Admin/Store/" + ns.Store.Id.ToString());
        }


        private bool Validate(NewStoreVM ns)
        {
            if (ns.ItemToAdd == null || ns.ItemToAdd.Id.Equals(new Guid()))
            {
                return false;
            }
            if (ns.Store == null || ns.Store.Id.Equals(new Guid()))
            {
                return false;
            }
            if (ns.ItemToAdd.SelectedAverableSize == null || ns.ItemToAdd.SelectedAverableSize.Size <= 0)
            {
                return false;
            }
            return true;
        }

        [HttpPost]
        public ActionResult Stores(StoreVM store)
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            _storeService.Add(_storeMapper.ConvertFromStoreVM(store));
            return Redirect("Stores");
        }

        [HttpPost]
        public ActionResult Index(ItemVM item)
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            Guid itemId = _itemService.Add(_itemMapper.ConvertFromVM(item)).Id;
            _pictureService.Add(item.Images, itemId);
            return Redirect("/Admin");
        }

        [HttpPost]
        public ActionResult Edit(ItemVM item)
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            _itemService.Update(_itemMapper.ConvertFromVM(item));
            if(item.Images.ElementAt(0) != null)
            {
                _pictureService.RemoveByItemId(item.Id);
                _pictureService.Add(item.Images, item.Id);
            }
            return Redirect("/Admin");
        }

        public ActionResult Edit(Guid id)
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            NewItemVM ni = new NewItemVM();
            ni.AllItems = _itemService.GetAll();
            ni.Item = _itemMapper.ConvertToVM(_itemService.FindById(id),0,"",new Guid());
            return View("Index", ni);
        }

        public ActionResult Remove(Guid id)
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            _siService.RemoveByItemId(id);
            _itemService.Remove(id);
            _pictureService.RemoveByItemId(id);
            return Redirect("/Admin");
        }

        [HttpPost]
        public ActionResult EditS(StoreVM store)
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            _storeService.Update(_storeMapper.ConvertFromStoreVM(store));
            return Redirect("/Admin/Stores");
        }

        public ActionResult EditS(Guid id)
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            NewStoreVM ni = new NewStoreVM();
            ni.AllStores = _storeService.GetAll();
            ni.Store = _storeMapper.ConvertToStoreVM(_storeService.FindById(id),null);
            return View("Stores", ni);
        }

        public ActionResult RemoveS(Guid id)
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            _siService.RemoveByStoreId(id);
            _storeService.Remove(id);
            return Redirect("/Admin/Stores");
        }

        public ActionResult RemoveItemFromStore(Guid storeId, Guid itemId)
        {
            if (!IsAdmin())
            {
                return Redirect("/");
            }
            _siService.RemoveByStoreIdAndItemId(storeId, itemId);
            return Redirect("/Admin/Store/" + storeId.ToString());
        }
    }
}

ShoeStore.Presentation/Controllers/CartController.cs
using ShoeShop.Presentation.Interfaces;
using ShoeStore.Models;
using ShoeStore.Presentation.Mappers;
using ShoeStore.Presentation.ViewModel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoeStore.Presentation.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        private IUserService _userService;
        private Configuration.Configurations _itemConfig;
        private CartMapper _cartMapper;

        public CartController()
        {
            _itemConfig = new Configuration.Configurations();
            _userService = _itemConfig.GetUserService();
            _cartMapper = new CartMapper();
        }

        public ActionResult MyItems()
        {
            return View((ICollection<ItemVM>)Session["cart"]);
        }

        public ActionResult Order()
        {
            User u = Session["userId"] == null ? new Models.User() : _userService.FindById((Guid)Session["userId"]);
            return View(u);
        }

        public ActionResult RemoveItemFromCart(Guid siId, double size)
        {
            ICollection<ItemVM> items = new List<ItemVM>();
            bool first = false;
            foreach (ItemVM item in (ICollection<ItemVM>)Session["cart"])
            {
                if (!item.StoreItemId.Equals(siId) || !size.Equals(item.SelectedAverableSize.Size) || first)
                {
                    items.Add(item);
                }
                else if (item.StoreItemId.Equals(siId))
                {
                    first = true;
                }
            }
            Session["cart"] = items;
            return Redirect("MyItems");
        }

        [HttpPost]
        public ActionResult Order(User user)
        {
            if (Session["userId"] != null)
            {
                _userService.Update(user);
            }
            _cartMapper.ResetCart(Session);
            return Redirect("/");
        }
    }
}

ShoeStore.Presentation/Controllers/ItemsController.cs
using ShoeShop.Presentation.Interfaces;
using ShoeStore.Configuration;
using ShoeStore.Models;
using ShoeStore.Presentation.Mappers;
using ShoeStore.Presentation.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoeStore.Presentation.Controllers
{
    public class ItemsController : Controller
    {
        private Configuration.Configurations _itemConfig;
        private IItemService _itemService;
        private ItemMapper _itemMapper;
        private CartMapper _cartMapper;

        public ItemsController()
        {
            _itemConfig = new Configuration.Configurations();
            _itemService = _itemConfig.GetItemService();
            _itemMapper = new ItemMapper(_itemConfig);
            _cartMapper = new CartMapper();
        }
        public ActionResult Item(Guid storeItemId)
        {
            ItemVM item = _itemMapper.GetItemByStoreItemId(storeItemId);
            return View(item);
        }

        [HttpPost]
        public ActionResult Item(ItemVM item)
        {
            //add to cart
            _cartMapper.AddItemToCart(item, Session);
            ItemVM oldItem = _itemMapper.GetItemByStoreItemId(item.StoreItemId);
            return View(oldItem);
        }
    }
}

ShoeStore.Presentation/Views/Shared/ItemPreview.cshtml
@model ShoeStore.Presentation.ViewModel.ItemVM

@{ 
    string image = "";
    if(Model.ImagesBit.Count != 0)
    {
        image = Model.ImagesBit.ElementAt(0);
    }
}
<div class="card effect">
    <a href="@Url.Action("Item", "Items", new { storeItemId = Model.StoreItemId})">
        <h1 style="white-space: nowrap; overflow-x: hidden">@Model.Model</h1>
        <div style="text-align:center">
            <img src="@image" height="150"/>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-6">
                <p>&nbsp;&nbsp;@Model.Sex</p>
            </div>
            <div class="col-md-6">
                <p>Price: @Model.Price</p>
            </div>
        </div>
     </a>
</div>

ShoeStore.Presentation/Views/Shared/Search.cshtml
@* Pretraga po
    
    -nazivu radnje
    -modelu patika
    -brendu patika
    -muske / zenske
    *@
@model ShoeStore.Presentation.ViewModel.SearchItem
<div class="panel-body">
    @using (Html.BeginForm("Search", "Home", FormMethod.Post))
    {
        <div class="form-group">
            @Html.TextBoxFor(model => Model.StoreName, htmlAttributes: new { @class = "form-control input-sm", placeholder = "Store Name", type = "text" })
        </div>
        <div class="form-group">
            @Html.TextBoxFor(model => Model.Brand, htmlAttributes: new { @class = "form-control input-sm", placeholder = "Brand", type = "text" })
        </div>
        <div class="form-group">
            @Html.TextBoxFor(model => Model.Model, htmlAttributes: new { @class = "form-control input-sm", placeholder = "Model", type = "text" })
        </div>
        <div class="form-group">
            @Html.TextBoxFor(model => Model.Sex, htmlAttributes: new { @class = "form-control input-sm", placeholder = "Sex", type = "text" })
        </div>
        <div class="form-group">
            <p>Size</p>
            @Html.TextBoxFor(model => Model.Size, htmlAttributes: new { @class = "form-control input-sm", placeholder = "Size", type = "text" })
        </div>
        <div class="form-group">
            <p>Minimum Price</p>
            @Html.TextAreaFor(model => Model.MinPrice, htmlAttributes: new { @class = "form-control input-sm", placeholder = "Minimum Price", type = "text" })
        </div>
        <div class="form-group">
            <p>Maximum Price</p>
            @Html.TextAreaFor(model => Model.MaxPrice, htmlAttributes: new { @class = "form-control input-sm", placeholder = "Maximum Price", type = "text" })
        </div>
        <input type="submit" value="Search" class="btn btn-info btn-block">
    }
</div>

ShoeStore.Presentation/Views/Shared/_AdminLayout.cshtml
@using ShoeStore.Presentation.ViewModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Admin</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="SHORTCUT ICON" href="https://www.freeiconspng.com/uploads/shoe-icon-26.png" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            background-color: #525252;
        }

        .centered-form {
            margin-top: 60px;
        }

            .centered-form .panel {
                background: rgba(255, 255, 255, 0.8);
                box-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;
            }

        table {
            border-collapse: collapse;
        }

        tr {
            border: none;
        }

        td {
            padding: 0 10px 0 10px;
        }

        th {
            padding: 0 10px 0 10px;
        }
    </style>
</head>
@{ 
    int itemsInCart = 0;
    if (Session["cart"] != null)
    {
        itemsInCart = ((ICollection<ItemVM>)Session["cart"]).Count;
    }
}
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Items", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Stores", "Stores", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Faculty of Technical Science Novi Sad</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ShoeStore.Presentation/Views/Shared/_Layout.cshtml
@using ShoeStore.Presentation.ViewModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Shoe Store</title>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <link rel="SHORTCUT ICON" href="https://www.freeiconspng.com/uploads/shoe-icon-26.png" />


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        body {
            background-color: #525252;
        }

        .centered-form {
            margin-top: 60px;
        }

            .centered-form .panel {
                background: rgba(255, 255, 255, 0.8);
                box-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;
            }
    </style>
</head>
@{ 
    int itemsInCart = 0;
    bool userLogged = true;
    if (Session["cart"] != null)
    {
        itemsInCart = ((ICollection<ItemVM>)Session["cart"]).Count;
    }
    if(Session["userId"] == null)
    {
        userLogged = false;
    }

}
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shoe Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @if (!userLogged)
                    {
                        <li>@Html.ActionLink("Registration", "Register", "Account")</li>
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                    }
                    <li>@Html.ActionLink(itemsInCart.ToString(), "MyItems", "Cart", new { }, new { @class = "glyphicon glyphicon-shopping-cart" , @style = "font-size: 20px; color: #33A1EE;" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Faculty of Technical Science Novi Sad</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>